server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-FORWARDED-FOR
  servlet:
      context-path: /myspringboot
      special-name: 我的SpringBoot

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  jackson:
   time-zone: GMT+8
   date-format: yyyy-MM-dd HH:mm:ss

